apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: arcalos-version-stream-update
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: arcalos-version-stream-update
            release: jx
        spec:
          containers:
          - args:
            - step
            - create
            - pr
            - versions
            - --repo
            - https://github.com/cloudbees/arcalos-jenkins-x-versions
            - --filter=*
            - --images
            - --excludes=jetstack/cert-manager
            - --excludes=jx-labs/jxl-boot
            - --excludes=stable/nginx-ingress  # Stick with 1.34.2 due to https://github.com/helm/charts/pull/21654 breaking upgrades
            - --batch-mode
            - --verbose
            command:
            - jx
            env:
            - name: GIT_COMMITTER_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_EMAIL
              value: jenkins-x@googlegroups.com
            - name: GIT_AUTHOR_NAME
              value: jenkins-x-bot
            - name: PIPELINE_KIND
              value: release
            image: gcr.io/jenkinsxio/builder-go:{{ .Values.versions.builders }}
            imagePullPolicy: IfNotPresent
            name: arcalos-version-stream-update
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: tekton-bot
  schedule: 0 */12 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
