apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-issue-lifecycle-close
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: jx-issue-lifecycle-close
            release: jx
        spec:
          containers:
          - image: gcr.io/k8s-prow/commenter:v20190528-0d7c4b53a
            command:
            - /app/robots/commenter/app.binary
            args:
            - --query=org:jenkins-x -label:lifecycle/frozen label:lifecycle/rotten
            - --updated=720h
            - --token=/etc/token/oauth
            - |-
              --comment=Rotten issues close after 30d of inactivity.
              Reopen the issue with `/reopen`.
              Mark the issue as fresh with `/remove-lifecycle rotten`.
              Provide feedback via https://jenkins-x.io/community.
              /close
            - --template
            - --ceiling=10
            - --confirm
            imagePullPolicy: IfNotPresent
            name: jx-issue-lifecycle-close
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - name: token
              mountPath: /etc/token
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: token
            secret:
              secretName: lighthouse-oauth-token
  schedule: 5 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
