---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jxui-backend-backup
  name: cloudbees-jxui-backend-backup
  namespace: jx
spec:
  description: Imported application for cloudbees/jxui-backend-backup
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jxui-backend-backup
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jxui-ts-client
  name: cloudbees-jxui-ts-client
  namespace: jx
spec:
  description: Imported application for cloudbees/jxui-ts-client
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jxui-ts-client
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jxui-frontend-backup
  name: cloudbees-jxui-frontend-backup
  namespace: jx
spec:
  description: Imported application for cloudbees/jxui-frontend-backup
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jxui-frontend-backup
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jx-tenant-service
  name: cloudbees-jx-tenant-service
  namespace: jx
spec:
  description: Imported application for cloudbees/jx-tenant-service
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jx-tenant-service
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: cb-app-slack
  name: cloudbees-cb-app-slack
  namespace: jx
spec:
  description: Imported application for cloudbees/cb-app-slack
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: cb-app-slack
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arcalos
  name: cloudbees-arcalos
  namespace: jx
spec:
  description: Imported application for cloudbees/arcalos
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arcalos
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arcalos-config
  name: cloudbees-arcalos-config
  namespace: jx
spec:
  description: Imported application for cloudbees/arcalos-config
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arcalos-config
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arcalos-setup
  name: cloudbees-arcalos-setup
  namespace: jx
spec:
  description: Imported application for cloudbees/arcalos-setup
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arcalos-setup
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arcalos-instance-template
  name: cloudbees-arcalos-instance-template
  namespace: jx
spec:
  description: Imported application for cloudbees/arcalos-instance-template
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arcalos-instance-template
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arcalosui-frontend
  name: cloudbees-arcalosui-frontend
  namespace: jx
spec:
  description: Imported application for cloudbees/arcalos-frontendui
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arcalosui-frontend
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arcalos-boot-config
  name: cloudbees-arcalos-boot-config
  namespace: jx
spec:
  description: Imported application for cloudbees/arcalos-boot-config
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arcalos-boot-config
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arcalos-jenkins-x-versions
  name: cloudbees-arcalos-jenkins-x-versions
  namespace: jx
spec:
  description: Imported application for cloudbees/arcalos-jenkins-x-versions
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arcalos-jenkins-x-versions
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: lighthouse-githubapp
  name: cloudbees-lighthouse-githubapp
  namespace: jx
spec:
  description: Imported application for cloudbees/lighthouse-githubapp
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: lighthouse-githubapp
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jx-repository-controller
  name: cloudbees-jx-repository-controller
  namespace: jx
spec:
  description: Imported application for cloudbees/jx-repository-controller
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jx-repository-controller
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jx-segment-controller
  name: cloudbees-jx-segment-controller
  namespace: jx
spec:
  description: Imported application for cloudbees/jx-segment-controller
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jx-segment-controller
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jx-arcalos-role-controller
  name: cloudbees-jx-arcalos-role-controller
  namespace: jx
spec:
  description: Imported application for cloudbees/jx-arcalos-role-controller
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jx-arcalos-role-controller
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: arch-docs
  name: cloudbees-arch-docs
  namespace: jx
spec:
  description: Imported application for cloudbees/arch-docs
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: arch-docs
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: tekton-sdm-app
  name: cloudbees-tekton-sdm-app
  namespace: jx
spec:
  description: Imported application for cloudbees/tekton-sdm-app
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: tekton-sdm-app
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: jx-sdm-app
  name: cloudbees-jx-sdm-app
  namespace: jx
spec:
  description: Imported application for cloudbees/jx-sdm-app
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: jx-sdm-app
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: rollout-sdm-app
  name: cloudbees-rollout-sdm-app
  namespace: jx
spec:
  description: Imported application for cloudbees/rollout-sdm-app
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: rollout-sdm-app
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: cloud-build-sdm-app
  name: cloudbees-cloud-build-sdm-app
  namespace: jx
spec:
  description: Imported application for cloudbees/cloud-build-sdm-app
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: cloud-build-sdm-app
---
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  labels:
    owner: cloudbees
    provider: github
    repository: saas-cli
  name: cloudbees-saas-cli
  namespace: jx
spec:
  description: Imported application for cloudbees/saas-cli
  provider: https://github.com
  providerName: github
  org: cloudbees
  repo: saas-cli
