dependencies:
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.459
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- condition: external-dns.enabled
  name: external-dns
  repository: https://charts.bitnami.com/bitnami
- name: jx-app-athens
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.17
- name: jx-app-sso
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.14
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- alias: jx-app-statusbadge
  condition: jx-app-statusbadge.enabled
  name: jx-app-statusbadge
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.7
- alias: ui
  name: jxui
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.1160
- name: plantuml
  repository: https://charts.gitlab.io/
  version: 0.1.12
- name: tekton-sdm-app
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.23
- name: jx-sdm-app
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.17
